### ISSUE TITLE
history replace throws errors

### ISSUE THREAD

**Issue by ahmedu007** [winoteam/react-router-navigation#76]
**Do you want to request a _feature_ or report a _bug_?**
Report a bug

**What is the current behavior?**
_If the current behaviour is a bug, please provide necessary steps for reproduction of this issue, or better the reduced test case (without any external dependencies, if possible)._

1. Okay so this error is really weird. Probably needs a bit more testing but its hard to reproduce it for even myself. I have history prop available in my component and I can use this.props.history.push('/login') without any issues. 

As soon as i change push to .replace I get this error

```
TypeError: undefined is not an object (evaluating 'scenes[targetSceneIndexInScenes].index')

This error is located at:
    in CardStack (at DefaultRenderer.js:137)
    in RCTView (at View.js:78)
    in View (at Transitioner.js:192)
    in Transitioner (at DefaultRenderer.js:151)
    in DefaultRenderer (at Navigation.js:42)
    in CardStack (created by Route)
    in Route (created by withRouter(CardStack))
    in withRouter(CardStack) (at Navigation.js:39)
    in Navigation (at App.js:58)
    in Router (created by MemoryRouter)
    in MemoryRouter (at NativeRouter.js:11)
    in NativeRouter (at App.js:57)
    in RCTView (at View.js:78)
    in View (at App.js:56)
    in ThemeProvider (at App.js:55)
    in App (created by Connect(App))
    in Connect(App) (at App.js:11)
    in Provider (at App.js:10)
    in NativeApp (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
```

I can use replace on most of my components in the app, but some places this error just persists and I'm struggling to clear history and block the user to go back to the screen they're not authorised to go back to.

**What is the expected behavior?**
Clear the last page and stop user from navigating back to it

**Environment (include versions). Did this work in previous versions?**

* Device: `macOS `
* OS: `iOS emulator running iOS 11.3`
* React-Native (version): `^0.54.2`
* React-Router (version): `^4.2.0`
* React-Router-Navigation (version): `^1.0.0-rc.4`

**Comment by ahmedu007** [comment]
Any suggestions, advice, instructions would be appreciated :)

**Comment by LeoLeBras** [comment]
Hi @ahmedu007 !
I'm facing similar issues with actual version of `react-router-navigation`. I'm fixing a lot of bugs on the [`dev`](https://github.com/LeoLeBras/react-router-navigation/tree/dev) branch including this one.
A stable version of the library should be released soon. 🙏

**Comment by ahmedu007** [comment]
Any progress on this issue?

**Comment by LeoLeBras** [comment]
Hey @ahmedu007 ,
Many changes have been made recently. Do you still have the error with the new `alpha` versions? If so, do you have an example (or a Github) repo that reproduces the issue?

**Comment by ahmedu007** [comment]
Hi @LeoLeBras 

Thanks for the response. The issue was fixed in alpha .6 but there was something else that wasnt working correctly in .7
We are staying on alpha.06 for now. I'll try to see if I can get around to replicate the issue, and give you more feedback. It was something along the lines of the `state.params` not being passed correctly or something.

**Comment by ahmedu007** [comment]
We can close this issue, as it seems to be working without any bugs for this specific case. Thankyou for all the efforts 💯

**Comment by LeoLeBras** [comment]
Okay, don't hesitate to send me a minimal repo to reproduce this issue !
