### ISSUE TITLE
location.state is set to new route's value before old route has finished animating out

### ISSUE THREAD

**Issue by extragalactic** [winoteam/react-router-navigation#84]
**Do you want to request a _feature_ or report a _bug_?**

Either a bug or I'm using it wrong.

**What is the current behavior?**

I have a Learn route which on-click opens a Results route via history.push, with the Results page title passed in via the state var. The Results page reads the title string via location.state.resultsPageTitle, and it renders correctly. However when I navigate back to the Learn route using history.goBack(), as soon as the page-out animation begins the location of my Results page is set to point to the Learn screen route... in this case location.state becomes undefined (and location.pathname becomes "/learn"). So the Results page will immediately crash since location.state is now undefined. Is this a bug, or am I using the routes or location prop incorrectly?

LearnScreen.js
```
onPress = () => {
      history.push({
        pathname: '/learn/results',
        state: {
          resultsPageTitle: 'Sneaky Results Title'
        }
      });
}

render() {
  <Navigation>
    <Card exact path="/learn" render={() => {
        ... Learn screen page, including a button that calls onPress above
      }
    />
    <Card exact path="/learn/results" render={({ location }) => <ResultsScreen location={location} />} />
  </Navigation>
}
```
ResultsScreen.js
```
render() {
  <Text>{this.props.location.state.resultsPageTitle}</Text>
}
```

**What is the expected behavior?**

I would expect that the page which is animating out to NOT receive an update to its location prop.

* Device: iPhone 7
* OS: iOS
* React-Native (version): 29.0.0, using Expo v29
* React-Router-Native* (version): 4.3.0
* React-Router-Navigation (version): 1.0.0-rc.4

**Comment by stevelacy** [comment]
Also experiencing this, need to do a check each time I access `props.location.state` to ensure it is not unset as it is transitioning out.

**Comment by LeoLeBras** [comment]
@stevelacy @extragalactic  Do you have an example (or a Github) repo that reproduces the issue?

**Comment by stevelacy** [comment]
Created: https://github.com/stevelacy/ReactRouterNativeTest
```
yarn 
Xcode -> Run
Click "Go to Page"
Click the header back button
```
<img width="378" alt="screen shot 2018-10-31 at 10 44 12" src="https://user-images.githubusercontent.com/5648999/47796358-8e2c4200-dcfa-11e8-96d6-38adccd0c278.png">

**Comment by LeoLeBras** [comment]
@stevelacy Awesome ! I'll take the time to look at it later this week ! 🤩

**Comment by stevelacy** [comment]
slick!

**Comment by stevelacy** [comment]
Can we get a alpha patch release soon? I'm editing the PropTypes.js file by hand to get the ViewPropTypes commit to work on the latest release
